pipeline {
    agent {
        node {
            label 'integration-tf' 
        }
    }
  stages {
    stage('PreBuild') {
      steps {
        sh '''
           export AWS_ACCESS_KEY_ID=XXXXXXXXXXXXXXXXX
           export AWS_SECRET_ACCESS_KEY=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
           export AWS_DEFAULT_REGION="us-east-1"
           rm -rf .terraform/
           make init
        '''
      }
    }
    stage('make plan') {
        steps {
            sh '''
               make plan
            '''
      }
    }
    stage('Make Apply') {
      steps {
            sh '''
               make apply -auto-approve
            '''
      }
        post{
            always{
                cleanWs()
            }
            success{
                //notification webhook
                echo 'Pipeline Execution Successfully Notification'
            }
            failure{
                //notification webhook
                echo 'Pipeline Execution Failed Notification'
            }
        }
    }
  }
  environment {
    region = 'us-east-1'
  }
}



